version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: task_management_system
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
        networks:
            - laravel_network
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=task_management_system
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret

    web:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: task_management_system
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        networks:
            - laravel_network
        volumes:
            - db_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: laravel
            PMA_PASSWORD: secret
        networks:
            - laravel_network
        depends_on:
            - db

networks:
    laravel_network:
        driver: bridge

volumes:
    db_data:
